fetch:
  data:
    url: "https://api.covid19api.com/summary"

#H2
spring:
  datasource:
    url: "jdbc:h2:mem:jpadb"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: "password"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
